import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
import Container from "@/components/blocks/Container";
import Tupperware from "@/components/blocks/Tupperware";
import { ConvexClientProvider } from "@/provider/ConvexClientProvider";

const barlow = Barlow({
	variable: "--font-barlow",
	weight: ["300", "400", "500", "600", "700"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${barlow.variable} antialiased`}>
				<GoogleOAuthProvider
					clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? ""}
				>
					<ConvexClientProvider>
						<Container>
							<Tupperware>{children}</Tupperware>
						</Container>
					</ConvexClientProvider>
				</GoogleOAuthProvider>
				<Toaster position="bottom-right" reverseOrder />
			</body>
		</html>
	);
}
